config/routes.rb
Rails.application.routes.draw do
  get 'resources/index'

  # get 'messages/new'
  resources :messages, only: [:new, :create]

  get 'password_resets/new'

  get 'password_resets/edit'

  resources :medications
  resources :addresses
  resources :todos
  get 'calendar/index'

  scope "(:locale)", :locale => /en|de/ do
    root :to => 'static_pages#home'
    get "static_page/home"
  end


  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  # route for data loading
  match "calendar/data", :to => "calendar#data", :as => "data", :via => "get"
  # route for data handling
  match "calendar/db_action", :to => "calendar#db_action", :as => "db_action", :via => "get"

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end


  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1><%= "#{t('about')}" %></h1>
	<h2>
		<% "#{t('caregiving_in_us')}" %>
	</h2>
<div class="about">
<div>
  <div>
		<a href="http://www.aarp.org/content/dam/aarp/ppi/2015/caregiving-in-the-united-states-2015-report-revised.pdf">
		<%= "#{t('aarp')}" %></a>
		<p><%= "#{t('2015_Report')}" %>: <%= "#{t('caregiving_in_us')}" %>.</p>
			<h3>
				<%= "#{t('key_findings')}" %>
			</h3>
				<h4>
					<%= "#{t('prevelence_of_caregiving')}" %>
				</h4>
					<p>
						<%= "#{t('estimated')}" %> <mark><strong> <%= "#{t('million')}" %> </strong></mark> <%= "#{t('adult_or_child')}" %>
					</p>
				<h4>
					<%= "#{t('basicts_caregiving')}" %>
				</h4>
					<p>
						<mark><%= "#{t('majority_of_caregivers')}" %> </mark> <%= "#{t('are_female')}" %> <mark> <%= "#{t('are_49')}" %> </mark> <%= "#{t('on_average_large')}" %>
					</p>
					<p>
						<%= "#{t('nearly_1_in_10')}" %>
					</p>
					<p>
						<%= "#{t('how_long')}" %> <mark> <%= "#{t('on_average_4')}" %> </mark> <%= "#{t('with_a_quarter')}" %>
					</p>
					<p>
						<%= "#{t('typical_care_recipient')}" %>
					</p>
					<p>
						[...]
					</p>
				<h4>
					<%= "#{t('primary_caregiver_status')}" %>
				</h4>
					<p>
						<mark><%= "#{t('over_six_in_10')}" %> </mark> <%= "#{t('meaning_either')}" %> <mark> <%= "#{t('the_37_percent')}" %> </mark>
					</p>
					<p>
						<%= "#{t('three_out_of_four')}" %>
					</p>
	<!-- Footnotes -->
	<h6>
		<%= "#{t('foot_note_7')}" %>
	</h6>
</div>
</div></div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1><%= "#{t('help')}" %></h1>
	<h2><%= "#{t('helpful_app_info')}" %></h2>
		<div class="help">
			<div>
  			<div>
					<h3><%= "#{t('home_page')}" %></h3>
						<ol>
							<%= "#{t('without_sigining_in')}" %>:
							<li><%= "#{t('help')}" %></li>
							<li><%= "#{t('about')}" %></li>
							<li><%= "#{t('contact')}" %></li>
							<li><%= "#{t('login')}" %></li>
							<li><%= "#{t('sign_up_now')}" %></li>
						</ol>
						<ol>
							<%= "#{t('once_you_signup')}" %>:
							<li><%= "#{t('feed')}" %></li>
							<li><%= "#{t('list_of_users')}" %></li>
							<li><%= "#{t('profile')}" %></li>
							<li><%= "#{t('settings')}" %></li>
							<li><%= "#{t('useful_tools')}" %></li>
								<ul>
									<li><%= "#{t('todo_list')}" %></li>
									<li><%= "#{t('addresses')}" %></li>
									<li><%= "#{t('medications')}" %></li>
								</ul>
						</ol>
				</div>
			</div>
		</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
<% provide(:title, 'Home') %>
<h1>Home - Shared Feed</h1>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Posts</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>

<div class="center jumbotron">
<div id="page-top">

  <div class="navbar-header">
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#about"><%= "#{t('about')}" %></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#features"><%= "#{t('features')}" %></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#pages"><%= "#{t('pages')}" %></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#signup"><%= "#{t('sign_up')}" %></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact"><%= "#{t('contact')}" %></a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
  </div>

  <header>
    <div class="header-content">
      <div class="header-content-inner">

        <!-- i18n locale -->
        <div class="locale">
            <p>
                <b><span style="color:black">I18n.locale:</span></b>
                <b><span style="color:white"><%= I18n.locale %></span></b>
            <br>
                <%= link_to_unless I18n.locale == :en, "English", locale: :en %>
                        |
                <%= link_to_unless I18n.locale == :de, "Deutsch", locale: :de %>
            </p>
        </div>

        <h1 id="homeHeading"><%= "#{t('welcome_to_TLCShare')}" %></h1>
          <br><br><br><br><br><br><br><br><br>
        <p>
          <a href="#about" class="btn btn-primary btn-xl page-scroll"><%= "#{t('find_out_more')}" %></a>
        </p>
      </div>
    </div>
  </header>

  <section class="bg-primary" id="about">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2 text-center">
          <h2 class="section-heading">
              <%= "#{t('a_place_for_caregivers')}" %>
          </h2>
          <hr class="light">
          <p class="text-faded">
              <%= "#{t('a_place_sub')}" %>
          </p>
          <a href="#features" class="page-scroll btn btn-default btn-xl sr-button">
              <%= "#{t('get_started')}" %>
          </a>
        </div>
      </div>
    </div>
  </section>

  <section id="features">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading">
              <%= "#{t('sign_up_features')}" %>
          </h2>
          <hr class="primary">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box">
            <i class="fa fa-4x fa-newspaper-o text-primary sr-icons"></i>
            <h3>
              <%= "#{t('informaiton_feed')}" %>
            </h3>
            <p class="text-muted">
              <%= "#{t('share_information')}" %>
            </p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box">
            <i class="fa fa-4x fa-diamond text-primary sr-icons"></i>
            <h3>
              <%= "#{t('organize')}" %>
            </h3>
            <p class="text-muted">
              <%= "#{t('private_place')}" %>
            </p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box">
            <i class="fa fa-4x fa-paper-plane text-primary sr-icons"></i>
            <h3>
              <%= "#{t('share')}" %>
            </h3>
            <p class="text-muted">
              <%= "#{t('share_with_cogivers')}" %>
            </p>
          </div>
        </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box">
              <i class="fa fa-4x fa-heart text-primary sr-icons"></i>
              <h3>
                <%= "#{t('understanding')}" %>
              </h3>
              <p class="text-muted">
                <%= "#{t('made_with_understanding')}" %>
              </p>
            </div>
          </div>
      </div>
    </div>
  </section>

  <section class="no-padding" id="pages">
    <br><br><br><br><br>
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading">
            <%= "#{t('sign_up_to_access')}" %>
          </h2>
          <hr class="primary">
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row no-gutter popup-gallery">
        <div class="col-lg-4 col-sm-6">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <div class="project-category text-faded">
                <%= "#{t('category')}" %>
              </div>
              <div class="project-name">
                <%= "#{t('home_share_feed')}" %>
              </div>
              <%=image_tag("screenShotHomeFeed.png", :class => "img-responsive") %>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-sm-6">
            <div class="portfolio-box-caption">
              <div class="portfolio-box-caption-content">
                <div class="project-category text-faded">
                  <%= "#{t('category')}" %>
                </div>
                <div class="project-name">
                  <%= "#{t('calendar')}" %>
                </div>
                <%=image_tag("screenShotCalendar.png", :class => "img-responsive") %>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-sm-6">
            <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    <%= "#{t('category')}" %>
                  </div>
                  <div class="project-name">
                    <%= "#{t('to_do_list')}" %>
                  </div>
                  <%=image_tag("screenShotTodos.png", :class => "img-responsive") %>
                </div>
            </div>
          </div>
          <div class="col-lg-4 col-sm-6">
            <div class="portfolio-box-caption">
              <div class="portfolio-box-caption-content">
                <div class="project-category text-faded">
                  <%= "#{t('category')}" %>
                </div>
                <div class="project-name">
                  <%= "#{t('medication_list')}" %>
                </div>
                <%=image_tag("screenShotMedications.png", :class => "img-responsive") %>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-sm-6">
            <div class="portfolio-box-caption">
              <div class="portfolio-box-caption-content">
                <div class="project-category text-faded">
                  <%= "#{t('category')}" %>
                </div>
                <div class="project-name">
                  <%= "#{t('addresses_and_contacts')}" %>
                </div>
                <%=image_tag("screenShotAddresses.png", :class => "img-responsive") %>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-sm-6">
            <div class="portfolio-box-caption">
              <div class="portfolio-box-caption-content">
                <div class="project-category text-faded">
                  <%= "#{t('category')}" %>
                </div>
                <div class="project-name">
                  <%= "#{t('resources')}" %>
                </div>
                <%=image_tag("screenShotResources.png", :class => "img-responsive") %>
              </div>
            </div>
          </div>
        </div>
    </div>
  </section>

  <section id="signup">
    <div class="container">
      <aside class="bg-dark">
        <div class="container text-center">
          <div class="call-to-action">
            <h2>
              <%= "#{t('sign_up_to_begin')}" %>
            </h2>
            <%= link_to t("sign_up_now"), signup_path, class: "btn btn-lg btn-primary" %>
          </div>
        </div>
      </aside>
    </div>
  </section>

  <section id="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2 text-center">
          <h2 class="section-heading">
            <%= "#{t('get_in_touch')}" %>
          </h2>
          <hr class="primary">
          <p>
            <%= "#{t('ready_to_start')}" %>
          </p>
          <p>
            <%= "#{t('questions')}" %>
          </p>
          <%= link_to t("contact"), new_message_path, class: "btn btn-lg btn-primary" %>
        </div>
        <div class="col-lg-4 col-lg-offset-2 text-center">
        </div>
        <div class="col-lg-4 text-center">
          <i class="fa fa-envelope-o fa-3x sr-contact"></i>
        </div>
      </div>
    </div>
  </section>

</div>
</div>

<% end %>