config/routes.rb
Rails.application.routes.draw do
  get 'resources/index'

  # get 'messages/new'
  resources :messages, only: [:new, :create]

  get 'password_resets/new'

  get 'password_resets/edit'

  resources :medications
  resources :addresses
  resources :todos
  get 'calendar/index'

  scope "(:locale)", :locale => /en|de/ do
    root :to => 'static_pages#home'
    get "static_page/home"
  end


  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  # route for data loading
  match "calendar/data", :to => "calendar#data", :as => "data", :via => "get"
  # route for data handling
  match "calendar/db_action", :to => "calendar#db_action", :as => "db_action", :via => "get"

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  	<div>
    	<p>Virginia Maroulakos Rucinski &copy;  <span id="year"></span></p>
    	<br>
  </small>




  <script>
  document.getElementById("year").innerHTML = new Date().getFullYear();
  </script>


</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "TLCshare", root_path, id: "logo" %>
    <div class="headernav">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t('home'), root_path %></li>
        <li><%= link_to t('help'), help_path %></li>
        <li><%= link_to t('statistics'),   about_path %></li>
        <li><%= link_to t('contact'), new_message_path %></li>     <!-- Sendgrid to be added -->
        <% if logged_in? %>
          <li><%= link_to t('users'), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= "#{t('useful_tools')}" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t('calendar'), calendar_index_path %></li>
              <li><%= link_to t('to_do_list'), todos_path %></li>
              <li><%= link_to t('addresses'), addresses_path %></li>
              <li><%= link_to t('medications'), medications_path %></li>
              <li><%= link_to t('resources'), resources_index_path %></li>
              <li class="divider"></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t('profile'), current_user %></li>
              <li><%= link_to t('settings'), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t('logout'), logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t('login'), login_path %></li>
        <% end %>
      </ul>
    </nav>
    </div>
  </div>
</div>>
</div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'bird.jpg' %>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                            'data-turbolinks-track': 'reload' %>



    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TLCsharei18n</title>


    <!-- Custom Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <div class=size>
      <%= yield %> 
      <div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/calendar_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'dhtmlxscheduler', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'dhtmlxscheduler', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'ext/dhtmlxscheduler_recurring', 'data-turbolinks-track' => true %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
  	<%= yield %>
  	<%= render 'layouts/footer' %>
  </body>
</html>